language: ruby
dist: xenial

before_install:
  - gem install bundler
  - rvm get update

install:
  - bundle install

addons:
  sonarcloud:
    organization: 'grupo-1-testing'
    token: $SONAR_TOKEN

script:
  - rubocop
  - rake test
  - sonar-scanner
