language: ruby
dist: xenial

before_install:
  - gem install bundler

install:
  - bundle install

addons:
  sonarcloud:
    organization: "vtespinosa_Proyecto-Testing"
    token: $SONAR_TOKEN

script:
  - rubocop
  - rake test
  - sonar-scanner